[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_ldf_mode = deep 

lib_deps = 
	SPI
	Wire
	adafruit/Adafruit BusIO @ ^1.14.1
	adafruit/Adafruit SHT31 Library @ ^2.2.2
	milesburton/DallasTemperature @ ^3.11.0
	knolleary/PubSubClient @ ^2.8